# ========== SERVER ==========
server.port=8080
server.servlet.context-path=/auth-api

# ========== APPLICATION ==========
spring.application.name=auth-api

# ========== PROFILE ==========
spring.profiles.active=dev
